yatube/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="home_page"),
    path("group/<slug:slug>", views.group_posts, name="group_posts"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
]

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name="name")
    slug = models.SlugField(unique=True, blank=True, null=True, default=None,
                            verbose_name="slug")
    description = models.TextField(verbose_name="description")

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="name")
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="author"
    )
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name="posts")

    class Meta:
        ordering = ["-pub_date"]

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    POSTS_PER_PAGE = 10
    posts = Post.objects.select_related("group")[:POSTS_PER_PAGE]
    context = {
        "posts": posts,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    POSTS_PER_PAGE = 10
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POSTS_PER_PAGE]
    context = {
        "group": group,
        "posts": posts,
    }
    return render(request, "posts/group_list.html", context)

yatube/templates/base.html
<!-- templates/posts/index.html -->
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="img/fav/fav.ico" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"> 
  <title>{% block title %}Главная страница{% endblock %}</title>
</head>
  <body>       
    <header>
      {% include "includes/header.html" %}
    </header>
    <main>
      <div class="container py-5"> 
        {% block content %}Тут что-то есть.{% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- templates/includes/footer.html -->
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!-- templates/includes/header.html -->
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:home_page" %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
  </div>
</nav>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
<title>
  {% block title %}{{ group.title }}{% endblock %}
</title>
{% block content %}
{% for post in posts %}
<p>
  {{ group.title }}
</p>
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>      
  <p>
    {{ post.text }}
  </p>         
</article>
<hr>
{% endfor %}
{% if not forloop.last %}<hr>{% endif %}
{% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends "base.html" %}
<title>
  {% block title %}Главная страница{% endblock %}
</title>
{% block content %} 
<h1>Последние обновления на сайте</h1>
{% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  {% if post.group %}   
  <a href="{% url "posts:group_posts" post.group.slug %}">все записи группы</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}